/**
 * useSignInToken — consume a Clerk "sign-in token" (ticket strategy) from the URL.
 *
 * Purpose: passwordless deep-link auth. When the KB-freshness email notifier embeds a
 * single-use ticket in the "Review Changes" URL, this hook auto-signs the user in so
 * they land directly on the destination without seeing the Clerk sign-in form.
 *
 * URL contract: `?token=<SIGN_IN_TOKEN>` — generated by the backend via Clerk's
 * POST /v1/sign_in_tokens. Tokens are single-use and expire (we issue with 60 min TTL).
 * The hook strips `?token=` from the URL after successful consumption so the token
 * doesn't linger in browser history / bookmarks / forwarded links.
 *
 * States:
 *   - 'idle'       → no token in URL OR user is already signed in
 *   - 'consuming'  → token is being exchanged with Clerk
 *   - 'success'    → session is active; URL has been cleaned of the token param
 *   - 'error'      → Clerk rejected the token (invalid / expired / already used);
 *                    the sign-in gate should render with the URL preserved so the
 *                    user can fall back to manual sign-in
 *
 * Caller integration (App.tsx):
 *   - While state === 'consuming', render a loading screen, NOT the sign-in form —
 *     we don't want to flash the sign-in UI then redirect.
 *   - While state === 'error', log the error + render the sign-in form as if there
 *     was no token at all. The user can sign in manually.
 */

import { useEffect, useRef, useState } from 'react';
// `@clerk/react` v6 (Core 3) moved useSignIn to a Signal-based API. The ticket-
// strategy flow we need here (single-use sign-in tokens) is only reachable via
// the legacy subpath, which re-exports the Core 2 hook shape — `{ signIn,
// setActive, isLoaded }` with `signIn.create({strategy, ticket})`. Clerk's own
// docs recommend `/legacy` for this flow under Core 3.
import { useSignIn } from '@clerk/react/legacy';
import { useClerk, useUser } from '@clerk/react';

export type SignInTokenState = 'idle' | 'consuming' | 'success' | 'error';

export interface UseSignInTokenResult {
  state: SignInTokenState;
  error: string | null;
}

/**
 * Strip `token` param from window.location without adding a history entry.
 * Preserves every other query param (e.g., `?h=HASH` remains intact).
 */
function stripTokenFromUrl(): void {
  if (typeof window === 'undefined') return;
  const url = new URL(window.location.href);
  if (!url.searchParams.has('token')) return;
  url.searchParams.delete('token');
  window.history.replaceState(null, '', url.pathname + (url.searchParams.toString() ? '?' + url.searchParams.toString() : '') + url.hash);
}

/**
 * Read the token param at hook mount. Reads from window.location (not useSearchParams)
 * because this hook typically runs BEFORE the React Router context is established
 * (the sign-in gate in App.tsx wraps the BrowserRouter).
 */
function readTokenFromUrl(): string | null {
  if (typeof window === 'undefined') return null;
  try {
    const url = new URL(window.location.href);
    return url.searchParams.get('token');
  } catch {
    return null;
  }
}

export function useSignInToken(): UseSignInTokenResult {
  const { signIn, setActive, isLoaded: signInLoaded } = useSignIn();
  const { isSignedIn, isLoaded: userLoaded } = useUser();
  const { signOut: _signOut } = useClerk();

  const [state, setState] = useState<SignInTokenState>('idle');
  const [error, setError] = useState<string | null>(null);

  // Ref-based guard against duplicate invocations. We can't depend on `state`
  // in the effect's deps array because a setState triggers re-run which fires
  // the cleanup function, which would cancel our own async work. Using a ref
  // lets us guard "already started" across renders without forcing re-runs.
  const startedRef = useRef(false);

  useEffect(() => {
    // Wait for Clerk to hydrate before making decisions. useSignIn and useUser
    // both expose `isLoaded`; we need both before proceeding.
    if (!signInLoaded || !userLoaded) return;

    // If already signed in, skip — don't consume a token against an existing
    // session. Strip the token anyway so it doesn't linger post-deep-link.
    if (isSignedIn) {
      if (readTokenFromUrl()) stripTokenFromUrl();
      return;
    }

    const token = readTokenFromUrl();
    if (!token) return;

    // One-shot guard — the token exchange should only run once per hook instance,
    // regardless of re-renders or effect re-runs.
    if (startedRef.current) return;
    startedRef.current = true;

    if (!signIn || !setActive) {
      setState('error');
      setError('Clerk sign-in client not ready');
      return;
    }

    setState('consuming');

    (async () => {
      try {
        const attempt = await signIn.create({ strategy: 'ticket', ticket: token });
        if (attempt.status !== 'complete') {
          setState('error');
          setError(`Sign-in incomplete (status: ${attempt.status}). Falling back to manual sign-in.`);
          return;
        }
        await setActive({ session: attempt.createdSessionId });
        stripTokenFromUrl();
        setState('success');
      } catch (err) {
        // Common causes: token expired, already consumed, signed for a different
        // Clerk instance. The user can still sign in manually — we don't block.
        setState('error');
        setError(err instanceof Error ? err.message : 'Sign-in token could not be consumed');
      }
    })();
  }, [signInLoaded, userLoaded, isSignedIn, signIn, setActive]);

  return { state, error };
}
