#!/usr/bin/env node

/**
 * Setup git hooks for CLAUDE.md maintenance
 *
 * Usage:
 *   node scripts/setup-hooks.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');
const GIT_HOOKS_DIR = path.join(ROOT_DIR, '.git', 'hooks');
const PRE_COMMIT_HOOK_PATH = path.join(GIT_HOOKS_DIR, 'pre-commit');
const PRE_COMMIT_SCRIPT = path.join(ROOT_DIR, 'scripts', 'pre-commit-claude-check.sh');

// ANSI colors
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  cyan: '\x1b[36m'
};

function main() {
  console.log(`${colors.bright}${colors.cyan}Setting up Git Hooks${colors.reset}\n`);

  // Check if .git directory exists
  if (!fs.existsSync(path.join(ROOT_DIR, '.git'))) {
    console.error(`${colors.red}Error: Not a git repository${colors.reset}`);
    console.error('Initialize git first: git init');
    process.exit(1);
  }

  // Create hooks directory if it doesn't exist
  if (!fs.existsSync(GIT_HOOKS_DIR)) {
    fs.mkdirSync(GIT_HOOKS_DIR, { recursive: true });
    console.log(`${colors.green}✓${colors.reset} Created .git/hooks directory`);
  }

  // Check if pre-commit hook already exists
  if (fs.existsSync(PRE_COMMIT_HOOK_PATH)) {
    const existingContent = fs.readFileSync(PRE_COMMIT_HOOK_PATH, 'utf8');

    if (existingContent.includes('pre-commit-claude-check.sh')) {
      console.log(`${colors.yellow}⚠${colors.reset} Pre-commit hook already configured`);
      return;
    }

    console.log(`${colors.yellow}⚠${colors.reset} Pre-commit hook already exists`);
    console.log('Backing up existing hook to pre-commit.backup');

    fs.copyFileSync(PRE_COMMIT_HOOK_PATH, `${PRE_COMMIT_HOOK_PATH}.backup`);
  }

  // Create symlink to pre-commit script
  try {
    // Make script executable
    execSync(`chmod +x "${PRE_COMMIT_SCRIPT}"`);

    // Create hook that calls our script
    const hookContent = `#!/bin/bash
# Auto-generated hook for CLAUDE.md maintenance
# Generated by: npm run setup:hooks

# Run CLAUDE.md check
"${PRE_COMMIT_SCRIPT}"
`;

    fs.writeFileSync(PRE_COMMIT_HOOK_PATH, hookContent, { mode: 0o755 });

    console.log(`${colors.green}✓${colors.reset} Pre-commit hook installed`);
    console.log(`${colors.green}✓${colors.reset} Hook will check for CLAUDE.md updates on commit`);

    console.log(`\n${colors.cyan}The hook will:${colors.reset}`);
    console.log('  1. Detect changes to package.json, esbuild.config.mjs, etc.');
    console.log('  2. Remind you to update CLAUDE.md if needed');
    console.log('  3. Validate CLAUDE.md if included in commit');
    console.log('  4. Allow you to proceed or abort the commit');

    console.log(`\n${colors.bright}To disable the hook:${colors.reset}`);
    console.log(`  rm .git/hooks/pre-commit`);

  } catch (error) {
    console.error(`${colors.red}Error setting up hook:${colors.reset}`, error.message);
    process.exit(1);
  }
}

main();
